name: test-on-commit

on:
  push:
    branches:
      - main

jobs:
  skip_check:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"  # 👈 evalúa el mensaje del commit
    runs-on: ubuntu-latest
    steps:
      - run: echo "✅ Ejecutando flujo de trabajo"
