name: Ejemplo usando secreto

on: [push] # cada vez que hagas push, se ejecutará

jobs:
  usar-secreto:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar nombre del repo
        run: echo "Este es el repositorio ${{ github.repository }}"

      - name: Usar secreto como variable de entorno
        env:
          CLAVE: ${{ secrets.MI_SECRETO }}
        run: |
          echo "Estoy usando el secreto como variable de entorno"
          echo "Valor del secreto (será censurado por GitHub): $CLAVE"
